// Generated by: gen
// TypeWriter: stringer
// Directive: +gen on Attribute

package vt100

import (
	"fmt"
)

const _Attribute_name = "Normal"

var _Attribute_index = [...]uint8{0, 6}

func (i Attribute) String() string {
	if i+1 >= Attribute(len(_Attribute_index)) {
		return fmt.Sprintf("Attribute(%d)", i)
	}
	return _Attribute_name[_Attribute_index[i]:_Attribute_index[i+1]]
}
