// Generated by: gen
// TypeWriter: stringer
// Directive: +gen on Color

package vt100

import (
	"fmt"
)

const _Color_name = "DefaultBlackRedGreenYellowBlueMagentaCyanWhite"

var _Color_index = [...]uint8{0, 7, 12, 15, 20, 26, 30, 37, 41, 46}

func (i Color) String() string {
	if i < 0 || i+1 >= Color(len(_Color_index)) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
