// Generated by: gen
// TypeWriter: stringer
// Directive: +gen on Intensity

package vt100

import (
	"fmt"
)

const _Intensity_name = "Normal"

var _Intensity_index = [...]uint8{0, 6}

func (i Intensity) String() string {
	if i < 0 || i+1 >= Intensity(len(_Intensity_index)) {
		return fmt.Sprintf("Intensity(%d)", i)
	}
	return _Intensity_name[_Intensity_index[i]:_Intensity_index[i+1]]
}
